//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesApi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamesApi.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;title&quot;: &quot;Uncharted 4&quot;,
        ///  &quot;description&quot;: &quot;For the first time ever in Uncharted history, drive vehicles during gameplay&quot;,
        ///  &quot;by&quot;: &quot;Sony&quot;,
        ///  &quot;platform&quot;: [
        ///    &quot;PS4&quot;
        ///  ],
        ///  &quot;age_rating&quot;: &quot;16&quot;,
        ///  &quot;likes&quot;: 100,
        ///  &quot;comments&quot;: [
        ///    {
        ///      &quot;user&quot;: &quot;bob&quot;,
        ///      &quot;message&quot;: &quot;Cracking game far too much cinematic&quot;,
        ///      &quot;dateCreated&quot;: &quot;2011-01-03&quot;,
        ///      &quot;like&quot;: 6
        ///    },
        ///    {
        ///      &quot;user&quot;: &quot;testingPriest&quot;,
        ///      &quot;message&quot;: &quot;Not enough shooting for me,far too easy &quot;,
        ///      &quot;dateCreated&quot;: &quot;2011- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ExampleJson {
            get {
                return ResourceManager.GetString("ExampleJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:1,&quot;value&quot;:{&quot;title&quot;:&quot;Uncharted 4&quot;,&quot;description&quot;:&quot;For the first time ever in Uncharted history, drive vehicles during gameplay&quot;,&quot;by&quot;:&quot;Sony&quot;,&quot;platform&quot;:[&quot;PS4&quot;],&quot;age_rating&quot;:&quot;16&quot;,&quot;likes&quot;:100,&quot;comments&quot;:[{&quot;user&quot;:&quot;bob&quot;,&quot;message&quot;:&quot;Cracking game far too much cinematic&quot;,&quot;dateCreated&quot;:&quot;1294085880&quot;,&quot;like&quot;:6},{&quot;user&quot;:&quot;testingPriest&quot;,&quot;message&quot;:&quot;Not enough shooting for me,far too easy &quot;,&quot;dateCreated&quot;:&quot;1301775480&quot;,&quot;like&quot;:5}]}},{&quot;id&quot;:2,&quot;value&quot;:{&quot;title&quot;:&quot;FIFA 19&quot;,&quot;description&quot;:&quot;For the first time ever in Uncharted hi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GamesArrayJson {
            get {
                return ResourceManager.GetString("GamesArrayJson", resourceCulture);
            }
        }
    }
}
